remove phanpy scratch
hpcugent/vsc_user_docs pull request #393
Opened 2020-10-21 09:41 UTC by hajgato

2020-10-21 10:58 UTC, boegel requested changes

2020-10-21 10:58 UTC, boegel commented on intro-HPC/ch_running_jobs_with_input_output_data.tex
> +\$VSC\_SCRATCH\_ARCANINE  & A separate (smaller) shared scratch filesystem, powered by SSDs. This scratch filesystem is intended for very I/O-intensive workloads. Note that this filesystem is not mou
`mounted` -> `available` (or `accessible`)

2020-10-21 12:29 UTC, hajgato commented on intro-HPC/ch_running_jobs_with_input_output_data.tex
> +\$VSC\_SCRATCH\_ARCANINE  & A separate (smaller) shared scratch filesystem, powered by SSDs. This scratch filesystem is intended for very I/O-intensive workloads. Note that this filesystem is not mou
@boegel fixed

2020-10-21 12:39 UTC, boegel approved these changes
lgtm

2020-10-21 14:21 UTC, hajgato commented
@boegel do you know why is it fails?

2020-10-21 14:21 UTC, hajgato commented
I mean travis.

2020-10-21 14:30 UTC, boegel commented
No, not really, no clear error...

@wpoely86 Any ideas?

2020-10-21 18:16 UTC, wpoely86 commented
No clue. It works locally for me. Judging by the error, it might be a travis issue. Did you try restart the tests?

2020-10-21 18:23 UTC, boegel commented
I restarted them once, trying again now...

2020-10-22 07:43 UTC, boegel commented
Keeps failing... :-/

One option we could try is switching to GitHub Actions for the CI, but that's not entirely trivial I think...

2020-10-23 09:49 UTC, wpoely86 commented
@hajgato can you merge/rebase on master? It should now use github actions instead of travis.

2020-10-24 10:37 UTC, merged