Fix some minor issues in docs
hpcugent/vsc_user_docs pull request #536
Opened 2023-08-08 08:22 UTC by xerbalind

2023-08-08 08:22 UTC, xerbalind commented on mkdocs/docs/HPC/FAQ.md
>  is a great resource for troubleshooting and looking up specifics.
is this still relevant?

2023-08-09 09:57 UTC, boegel requested changes

2023-08-09 09:57 UTC, boegel commented on mkdocs/docs/HPC/FAQ.md
> +New users should consult the [Introduction to HPC](../introduction)
```suggestion
New users should consult the [Introduction to HPC](introduction.md)

2023-08-09 09:57 UTC, boegel commented on mkdocs/docs/HPC/FAQ.md
>  is a great resource for troubleshooting and looking up specifics.
No, not really, I would reword it to:

```
New users should consult the Introduction to HPC 
to get started, which is a great resource for learning the basics, troubleshooting, and looking up specifics.
```

2023-08-09 09:57 UTC, boegel commented on mkdocs/docs/HPC/index.md
> +switch to different operating system, click [here](../#force_select_OS).
```suggestion
To switch to different operating system (Windows, macOS, Linux), click [here](../#force_select_OS).

2023-08-09 09:57 UTC, boegel commented on mkdocs/docs/HPC/index.md
> +This is the documentation from the point of view of a **{{ OS }}** user.
```suggestion
The current view of the documentation is intended for people using **{{ OS }}* as operating system.

2023-08-09 09:57 UTC, boegel commented on mkdocs/docs/HPC/program_examples.md
> +If you have **not done already** copy our examples to your home directory:
```suggestion
If you have **not done so already** copy our examples to your home directory by running the following command:
```

Maybe also add a note to explain what `~` is (or point to a section where that's explained)

2023-08-09 09:57 UTC, boegel commented on mkdocs/docs/HPC/running_batch_jobs.md
> +software works on the login nodes. See [the section on Running software that is incompatible with host](../troubleshooting/#running-software-that-is-incompatible-with-host) for why this is and how to
```suggestion
software works on the login nodes. See [the section on Running software that is incompatible with host](troubleshooting.md#running-software-that-is-incompatible-with-host) for why this is and how to fix

2023-08-10 08:59 UTC, boegel approved these changes

2023-08-10 08:59 UTC, merged