Module list detail
hpcugent/vsc_user_docs pull request #559
Opened 2023-08-28 08:55 UTC by milachae

PR with the detailed overviews of all the software.
First merge #554 before this.

#553

2023-08-31 14:06 UTC, milachae commented
@boegel 
ready for review

2023-08-31 16:07 UTC, boegel requested changes
- rename `module_overview.py` to `available_software.py`
- collapse `module_detail.py` in `available_software.py`
- add a `README.txt` in `data/` and `detail/` subdirs

2023-09-01 06:55 UTC, milachae commented
@boegel 
I applied all suggestions!


At this moment, this is the current look of the detail pages:
![image](https://github.com/hpcugent/vsc_user_docs/assets/95340152/9c780a71-739b-4d9d-8ba2-83688c71f202)

2023-09-01 08:31 UTC, boegel approved these changes

2023-09-01 08:31 UTC, merged