html to md for qsub code example
hpcugent/vsc_user_docs pull request #669
Opened 2024-08-19 15:45 UTC by lbarraga

In this pull request I will try to convert as much html to plain markdown as possible

2024-08-20 14:59 UTC, lbarraga commented
negative side effects: 

- commands in code blocks are no longer bold: 
![image](https://github.com/user-attachments/assets/92a57a2f-dde4-42e2-ac1e-e90962412cac)
vs 
![image](https://github.com/user-attachments/assets/c4bf54a5-8224-4291-b841-dbad1b57c521)

- Tables cannot be styled less (see title text not centered):
![image](https://github.com/user-attachments/assets/8917dc63-1bfa-4c84-82bc-7d51f251a876)
vs
![image](https://github.com/user-attachments/assets/8bc0a752-6799-43ab-acb9-11e6857fd811)

2024-08-20 15:13 UTC, stdweird commented
what in the diff causes the table layout changes?

2024-08-20 15:14 UTC, boegel commented
> what to do with these kinds of comments?
> 
> ```
> <!-- 
> %% Kurt Lust: I've hidden the first part of this chapter as mmlsquota is only
> %% for GPFS file systems (and not for , e.g., the NetApp in Leuven for home and data)
> %% and as on several clusters, the explicit path is needed.
> % In general it may be useful to see how much space (in KB) and how many files that you are using on any file system.  This information is also shown each time that you log in to the {{hpc}}
> 
> % \begin{prompt}
> % %\shellcmd{mmlsquota}%
> %                          Block Limits
> % Filesystem   type     KB     quota     limit  in_doubt  grace
> % data          USR  82944  26214400  28835840         0   none
> % home          USR  34560   3145728   3461120         0   none
> % scratch       USR  29472  26214400  28835840     19456   none
> 
> % |      File Limits
> % Filesystem  files   quota   limit in_doubt  grace  Remarks
> % Data           27  100000  150000        0   none
> % Home          117   20000   25000        0   none
> % Scratch        11  100000  150000       20   none
> % \end{prompt} 
> -->
> ```
> 
> I have came across other weird "prompt" comments

Just remove them, we still have them in Git history?

2024-08-20 15:14 UTC, boegel commented
> what in the diff causes the table layout changes?

Not using `<center>` HTML tags anymore, probably?

2024-08-20 15:16 UTC, stdweird commented
i mean in this diff? i can't find the changes.

2024-08-20 15:27 UTC, stdweird commented
i am merely wondering if the alignment works across multiple dividers. mkdocs needs an extension, not sure we already have it https://squidfunk.github.io/mkdocs-material/reference/data-tables/#configuration

so to try

```
| col1 | col 2 |
| :---:   | :---:    |
| centered | centered |
| :--- | ---: |
| left |  right |
```

2024-08-21 07:45 UTC, lbarraga commented
> i am merely wondering if the alignment works across multiple dividers. mkdocs needs an extension, not sure we already have it https://squidfunk.github.io/mkdocs-material/reference/data-tables/#configuration
> 
> so to try
> 
> ```
> | col1 | col 2 |
> | :---:   | :---:    |
> | centered | centered |
> | :--- | ---: |
> | left |  right |
> ```

We are able to use this without loading an extra extension. The problem is that this centers the text in the cell, while the original html centers the text over the whole row. I have updated the image so the subtitle is in the second row (maybe this looks a bit more pleasing to the eye).

Another solution might also be to split this table into two tables with normal md titles for "long term storage" and "fast temporary storage"

2024-08-21 07:49 UTC, lbarraga commented
> i mean in this diff? i can't find the changes.

That is my bad, I did not commit this yet. See next commit

2024-08-21 09:05 UTC, lbarraga commented
I used the title feature for code blocks to get rid of the center tags before a codeblock:

![image](https://github.com/user-attachments/assets/3fe2e1fe-2053-4ff9-98f1-b6a195840904)

vs

![image](https://github.com/user-attachments/assets/ed15a856-964f-4a0d-8fb6-02bcffc1d53e)


\```C title="T_hello.c"
....
\```

2024-08-21 09:24 UTC, lbarraga commented
Images are no longer centered (left vs right):

![image](https://github.com/user-attachments/assets/4e527865-5578-4b47-9f6f-fb1a97499dda)

2024-08-21 13:45 UTC, lbarraga commented
In the original docs, HTML line breaks were used (`<br/>`) to render the last row of the following table:

![image](https://github.com/user-attachments/assets/d498173a-bda5-4d50-bc90-7a08f90641b4)

This cannot be replicated in plain markdown. So I solved it like this:

![image](https://github.com/user-attachments/assets/0e72998f-29ec-4d5c-a9f3-bd9e1bcb24fd)

2024-08-21 13:47 UTC, lbarraga commented
This tables contained wrongly rendered `\newline`:
![image](https://github.com/user-attachments/assets/121a6159-1304-4316-b4d5-6942a7918b9c)

It is now:

![image](https://github.com/user-attachments/assets/ba0948e3-9e92-4aa6-845c-ebf2926ef576)

2024-08-21 14:34 UTC, lbarraga commented
`gpu.md` contains multiple html TODO comments. Should these be kept, removed or converted to issues?

2024-08-21 14:48 UTC, boegel commented
> `gpu.md` contains multiple html TODO comments. Should these be kept, removed or converted to issues?

If you can't keep them easily commented out, then remove them and open issues for them

2024-08-22 14:20 UTC, lbarraga commented
Besides HTML tags, I also see some images styled like this:

```
![image](img/ch0-hpc.png){: align=left style="height:383px;width:378px;border-radius:6px" }
```

I will not touch this as this seems deliberate.

2024-08-27 16:14 UTC, boegel requested changes
I've gone through this in details, looks great, thanks a lot for the effort on this one @lbarraga!

I've made a large bunch of suggestions for tiny edits, which I'll apply myself.

They pretty much all consist of removing `$ ` in code blocks which only specify a command to run,  which makes them a lot easier to copy-paste, so I took the opportunity to improve that a lot while reviewing this...

2024-08-27 16:14 UTC, boegel commented on mkdocs/docs/HPC/running_interactive_jobs.md
> +$ cd ~/{{ exampledir }}
```suggestion
cd ~/{{ exampledir }}

2024-08-27 16:14 UTC, boegel commented on mkdocs/docs/HPC/running_jobs_with_input_output_data.md
> +$ cd ~/{{ exampledir }}
```suggestion
cd ~/{{ exampledir }}

2024-08-27 16:14 UTC, boegel commented on mkdocs/docs/HPC/running_jobs_with_input_output_data.md
> +$ kinit yourugentusername@UGENT.BE -r 7d
```suggestion
kinit yourugentusername@UGENT.BE -r 7

2024-08-27 16:14 UTC, boegel commented on mkdocs/docs/HPC/running_jobs_with_input_output_data.md
> +$ kinit -R
```suggestion
kinit -R

2024-08-27 16:14 UTC, boegel commented on mkdocs/docs/HPC/running_jobs_with_input_output_data.md
> +$ krenew -b -K 60
```suggestion
krenew -b -K 60

2024-08-27 16:14 UTC, boegel commented on mkdocs/docs/HPC/sites/gent/available-modules.md
> +$ module av matlab
```suggestion
module avail matlab

2024-08-27 16:14 UTC, boegel commented on mkdocs/docs/HPC/troubleshooting.md
> +qsub fibo.pbs
```suggestion
$ qsub fibo.pbs

2024-08-27 16:14 UTC, boegel commented on mkdocs/docs/HPC/troubleshooting.md
> +ssh {{userid}}@{{loginnode}}
```suggestion
$ ssh {{userid}}@{{loginnode}}

2024-08-27 16:14 UTC, boegel commented on mkdocs/docs/HPC/useful_linux_commands.md
> +$  info ls
```suggestion
$ info ls

2024-08-27 16:14 UTC, boegel commented on mkdocs/docs/HPC/useful_linux_commands.md
> +$ nano foo
```suggestion
nano foo

2024-08-27 16:14 UTC, boegel commented on mkdocs/docs/HPC/useful_linux_commands.md
> +$  chmod +x foo
```suggestion
chmod +x foo

2024-08-27 16:14 UTC, boegel commented on mkdocs/docs/HPC/x2go.md
> +$ hostname
```suggestion
hostname

2024-08-27 16:25 UTC, boegel approved these changes

2024-08-27 16:25 UTC, merged