Link checker
hpcugent/vsc_user_docs pull request #696
Opened 2024-09-09 16:55 UTC by lbarraga

This PR contains a scripts that filters a-tags out of the HTML in the build files and checks if they exist. For more info check the included README

2024-09-10 18:09 UTC, boegel commented
@lbarraga Can you also add the whitelist file that makes sense (for example the `account.vscentrum.be` URLs, for which we get HTTP status code 500 since we're not logged in), and a GitHub Actions workflow to run this link checker script (I'm guessing it will have to be included as an extra step in the existing build workflow, since we need to built HTML)

2024-09-13 11:38 UTC, lbarraga commented
@boegel Ready for review

2024-09-19 11:31 UTC, boegel requested changes

2024-09-19 11:31 UTC, boegel commented on scripts/link_checker/README.md
> +$ ./link_checker.sh /path/to/mkdocs/build > links.txt
```suggestion
$ ./generate_links_from_build.sh /path/to/mkdocs/build > links.txt

2024-09-19 11:31 UTC, boegel commented on scripts/link_checker/README.md
> +$ python link_checker.py [--whitelist <whitelist.txt>] links.txt
```suggestion
$ python check_links.py [--whitelist <whitelist.txt>] links.txt

2024-09-19 11:32 UTC, boegel approved these changes

2024-09-19 11:46 UTC, boegel commented
@lbarraga Your link checker works really well, https://wiki.openfoam.com/Tutorials seems to be broken now :)

2024-09-19 15:37 UTC, lbarraga commented
only had to re-run the build. Link seems ok now.

2024-09-19 15:46 UTC, merged